### ISSUE TITLE
examples/bcc/perf/perf.go needs refactoring

### ISSUE THREAD

**Issue by greenpau** [iovisor/gobpf#255]
```
$ go version
go version go1.14.2 linux/amd64
```

The error:

```
$ go run examples/bcc/perf/perf.go
# github.com/iovisor/gobpf/bcc
bcc/module.go:98:40: too many arguments in call to _Cfunc_bpf_module_create_c_from_string
        have (*_Ctype_char, number, **_Ctype_char, _Ctype_int, _Ctype__Bool, nil)
        want (*_Ctype_char, _Ctype_uint, **_Ctype_char, _Ctype_int, _Ctype__Bool)
bcc/module.go:230:28: too many arguments in call to _C2func_bcc_func_load
        have (unsafe.Pointer, _Ctype_int, *_Ctype_char, *_Ctype_struct_bpf_insn, _Ctype_int, *_Ctype_char, _Ctype_uint, _Ctype_int, *_Ctype_char, _Ctype_uint, nil)
        want (unsafe.Pointer, _Ctype_int, *_Ctype_char, *_Ctype_struct_bpf_insn, _Ctype_int, *_Ctype_char, _Ctype_uint, _Ctype_int, *_Ctype_char, _Ctype_uint)
```

**Comment by greenpau** [comment]
Looks like it is related to the change https://github.com/iovisor/gobpf/pull/210

**Comment by greenpau** [comment]
It looks like `bcc/module.go` needs to be adjusted to work with older kernels. I am running it on `3.10.0-1127.18.2.el7.x86_64` (CentOS 7) and it does not work because of the function change.

https://github.com/iovisor/gobpf/blob/e6b321d3210387d6a09bde4feba22a09e8c6f4ae/bcc/module.go#L98

**Comment by mauriciovasquezbernal** [comment]
Could you check the BCC version you have installed? IIRC it's not related to the kernel version but to the BCC. It should work with BCC >= 0.11.0.

**Comment by greenpau** [comment]
@mauriciovasquezbernal , thank you for your response! Greatly appreciated!

I am using  `0.10` on CentOS 7.

```
# rpm -qa | grep bcc
bcc-tools-0.10.0-1.el7.x86_64
python-bcc-0.10.0-1.el7.x86_64
bcc-devel-0.10.0-1.el7.x86_64
bcc-0.10.0-1.el7.x86_64
```

**Comment by mauriciovasquezbernal** [comment]
@greenpau you're welcome!

In order to use gobpf you'll have to either update your BCC version (>= 0.11) or use an old version of gobpf (previous to [this commit](https://github.com/iovisor/gobpf/commit/cda73bdde3bf14fc898d07b8936073e1aa197708)). 
I highly recommend to update your BCC version so you don't get stuck with an old version that doesn't receive any update.
