### ISSUE TITLE
it occured not enouph params

### ISSUE THREAD

**Issue by carolove** [iovisor/gobpf#95]
https://github.com/iovisor/gobpf/blob/659416c3ebd49c666e9e0682739eefa9915594a5/bcc/module.go#L175

paltform: linux 4.10, ubuntu 16.04,
steps:
run: ~/gopath/src/github.com/iovisor/gobpf/examples/bcc/bash_readline$ go build -o main
it shows,
# github.com/iovisor/gobpf/bcc
../../../bcc/module.go:175: not enough arguments in call to _C2func_bpf_prog_load
        have (uint32, *C.struct_bpf_insn, C.int, *C.char, C.uint, *C.char, C.uint)
        want (uint32, *C.char, *C.struct_bpf_insn, C.int, *C.char, C.uint, *C.char, C.uint)

**Comment by schu** [comment]
gobpf supports bcc v0.4.0 (the latest release currently) and not master. It looks like you are using master?

**Comment by schu** [comment]
Closing this issue as it should work with bcc 0.4.0
